### ISSUE TITLE
Change the colour scale from red to something else

### ISSUE THREAD

**Issue by davanstrien** [DavidBeavan/coronavirus_covid-19#5]
Red negatively/can be associated with mortality. Using another colour scale has been suggested in a number of pieces to be more suitable for this situation. For example, see: 
- https://www.esri.com/arcgis-blog/products/product/mapping/mapping-coronavirus-responsibly/
- https://medium.com/nightingale/ten-considerations-before-you-create-another-chart-about-covid-19-27d3bd691be8

**Comment by DavidBeavan** [comment]
Good point, and thanks for the references... I need to manage two colour scales, one for raw counts and one for normalised counts (cases per population). Blue and purple respectively seems to work... stay tuned.

**Comment by davanstrien** [comment]
👌
